# Generated by Django 5.2.17 on 2026-09-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='year',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
